import { type Keys } from "../../interfacesAndTypes"

export const GKeys: Keys = [
	{ name: "D", espacio: true, number: 32, isBlackKey: false },
	{ name: "C#", espacio: false, number: 31, isBlackKey: true },
	{ name: "C", espacio: false, number: 30, isBlackKey: false },
	{ name: "B", espacio: true, number: 29, isBlackKey: false },
	{ name: "A#", espacio: false, number: 28, isBlackKey: true },
	{ name: "A", espacio: false, number: 27, isBlackKey: false },
	{ name: "G#", espacio: false, number: 26, isBlackKey: true },
	{ name: "G", espacio: true, number: 25, isBlackKey: false },
	{ name: "F#", espacio: false, number: 24, isBlackKey: true },
	{ name: "F", espacio: false, number: 23, isBlackKey: false },
	{ name: "E", espacio: true, number: 22, isBlackKey: false },
	{ name: "D#", espacio: false, number: 21, isBlackKey: true },
	{ name: "D", espacio: false, number: 20, isBlackKey: false },
	{ name: "C#", espacio: false, number: 19, isBlackKey: true },
	{ name: "C", espacio: true, number: 18, isBlackKey: false },
	{ name: "B", espacio: false, number: 17, isBlackKey: false },
	{ name: "A#", espacio: false, number: 16, isBlackKey: true },
	{ name: "A", espacio: true, number: 15, isBlackKey: false },
	{ name: "G#", espacio: false, number: 14, isBlackKey: true },
	{ name: "G", espacio: false, number: 13, isBlackKey: false },
	{ name: "F#", espacio: false, number: 12, isBlackKey: true },
	{ name: "F", espacio: true, number: 11, isBlackKey: false },
	{ name: "E", espacio: false, number: 10, isBlackKey: false },
	{ name: "D#", espacio: false, number: 9, isBlackKey: true },
	{ name: "D", espacio: true, number: 8, isBlackKey: false },
	{ name: "C#", espacio: false, number: 7, isBlackKey: true },
	{ name: "C", espacio: false, number: 6, isBlackKey: false },
	{ name: "B", espacio: true, number: 5, isBlackKey: false },
	{ name: "A#", espacio: false, number: 4, isBlackKey: true },
	{ name: "A", espacio: false, number: 3, isBlackKey: false },
	{ name: "G#", espacio: false, number: 2, isBlackKey: true },
	{ name: "G", espacio: true, number: 1, isBlackKey: false },
]
